# Generated by Django 5.0.2 on 2024-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Goal Categories',
            },
        ),
    ]
