# Generated by Django 5.0.2 on 2024-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completion_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
