# Generated by Django 5.0.2 on 2024-03-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
